###
POST http://localhost:9000/api/user HTTP/1.1
Content-Type: application/json
{
      
        "name": "nuevo1",
        "password": "hghghg",
        "email": "emaildeexample@example"
       
  }

###
  GET http://localhost:9000/api/user/63779d1a3a74385cade928c3 HTTP/1.1
Content-Type: application/json


###

PUT  http://localhost:9000/api/user/63779d1a3a74385cade928c3 HTTP/1.1
Content-Type: application/json

{
    "email": "ooooooooo",
    "name": "editando el nuevo",
    "password": "editado"
}

###
DELETE http://localhost:9000/api/user/63779f06f5fab1fde6fefb56 HTTP/1.1
Content-Type: application/json

