###
GET  http://localhost:9000/api/producto HTTP/1.1

###

GET  http://localhost:9000/api/producto/63711b82f98388e7bdede249 HTTP/1.1
###
POST http://localhost:9000/api/producto HTTP/1.1
Content-Type: application/json

{
    "title" : "producto 5",
    "price" : 3000,
    "description" : "desde local a db ejemplo 3",
    "images": ["https://api.lorem.space/image/burger?w=150&h=150"]
}
###

PUT http://localhost:9000/api/producto/6372812f058dbccb8f54b9d8 HTTP/1.1
Content-Type: application/json

{
    
    "title": "hhhhhamburguesa",
    "price": 1000,
    "description": "desde local a db ejemplo 2",
    
  }

###
DELETE http://localhost:9000/api/producto/63711b82f98388e7bdede249 HTTP/1.1
Content-Type: application/json