###
POST http://localhost:9000/api/producto HTTP/1.1
Content-Type: application/json


{
    "title": "HAMBURGUESA TODOTERRENO",
    "price": 15000,
    "description": "Dos carnes de 125g cada una 100%      de         res a la parrilla con salsa BBQ"
}
###
  GET http://localhost:9000/api/producto/ HTTP/1.1
Content-Type: application/json


###

PUT  http://localhost:9000/api/user/63779d1a3a74385cade928c3 HTTP/1.1
Content-Type: application/json

{
    "email": "ooooooooo",
    "name": "editando el nuevo",
    "password": "editado"
}

###
DELETE http://localhost:9000/api/user/63779d82a13e35f4ab621633 HTTP/1.1
Content-Type: application/json

